#!/usr/bin/env bash
set -euo pipefail

IMAGE_NAME=${IMAGE_NAME:-tytn/batchbench:cu126}

# Shared directory for generated request payloads and logs
OUTPUT_DIR=${OUTPUT_DIR:-$(pwd)/outputs}
mkdir -p "$OUTPUT_DIR"

export BATCHBENCH_MODE=online

# vLLM server configuration
export ONLINE_MODEL=${ONLINE_MODEL:-Qwen/Qwen3-0.6B}
export ONLINE_TENSOR_PARALLEL_SIZE=${ONLINE_TENSOR_PARALLEL_SIZE:-1}
export ONLINE_PIPELINE_PARALLEL_SIZE=${ONLINE_PIPELINE_PARALLEL_SIZE:-1}
export ONLINE_MAX_NUM_BATCHED_TOKENS=${ONLINE_MAX_NUM_BATCHED_TOKENS:-1024}
export ONLINE_GPU_MEMORY_UTILIZATION=${ONLINE_GPU_MEMORY_UTILIZATION:-0.75}
  
# Dataset generation options
export ONLINE_GENERATE_TOKENIZER_MODEL=${ONLINE_GENERATE_TOKENIZER_MODEL:-$ONLINE_MODEL}
export ONLINE_DATASET_PATH=${ONLINE_DATASET_PATH:-/outputs/requests.jsonl}
export ONLINE_GENERATE_COUNT=${ONLINE_GENERATE_COUNT:-32}
export ONLINE_GENERATE_PREFIX_OVERLAP=${ONLINE_GENERATE_PREFIX_OVERLAP:-0.0}
export ONLINE_GENERATE_APPROX_INPUT_TOKENS=${ONLINE_GENERATE_APPROX_INPUT_TOKENS:-256}

# vLLM timeout options
export ONLINE_SERVER_WAIT_RETRIES=${ONLINE_SERVER_WAIT_RETRIES:-600}
export ONLINE_SERVER_WAIT_DELAY_SECS=${ONLINE_SERVER_WAIT_DELAY_SECS:-3}

# Online benchmark client parameters
export ONLINE_CLIENT_MODEL=${ONLINE_CLIENT_MODEL:-$ONLINE_MODEL}
export ONLINE_USERS=${ONLINE_USERS:-4}
export ONLINE_REQUESTS_PER_USER=${ONLINE_REQUESTS_PER_USER:-1}
export ONLINE_REQUEST_TIMEOUT_SECS=${ONLINE_REQUEST_TIMEOUT_SECS:-120}

exec docker run --rm \
  --gpus all \
  -p 8000:8000 \
  -e BATCHBENCH_MODE \
  -e ONLINE_MODEL \
  -e ONLINE_TENSOR_PARALLEL_SIZE \
  -e ONLINE_PIPELINE_PARALLEL_SIZE \
  -e ONLINE_MAX_NUM_BATCHED_TOKENS \
  -e ONLINE_GPU_MEMORY_UTILIZATION \
  -e ONLINE_SERVER_WAIT_RETRIES \
  -e ONLINE_SERVER_WAIT_DELAY_SECS \
  -e ONLINE_DATASET_PATH \
  -e ONLINE_GENERATE_COUNT \
  -e ONLINE_GENERATE_TOKENIZER_MODEL \
  -e ONLINE_GENERATE_PREFIX_OVERLAP \
  -e ONLINE_GENERATE_APPROX_INPUT_TOKENS \
  -e ONLINE_CLIENT_MODEL \
  -e ONLINE_USERS \
  -e ONLINE_REQUESTS_PER_USER \
  -e ONLINE_REQUEST_TIMEOUT_SECS \
  -v "$OUTPUT_DIR":/outputs \
  "$IMAGE_NAME"
