#!/bin/bash
#
# BatchBench Container Startup Script
# 
# This script mimics the Docker entrypoint from Dockerfile.cu126 but allows you
# to edit it for custom compute providers that require a bash script on startup.
#
# Usage:
#   1. Edit the configuration section below
#   2. Copy this script to your container or mount it
#   3. Run: bash launch_batchbench.sh
#
# The script will:
#   1. Generate a YAML config file
#   2. Invoke run_docker.py (the batchbench-entrypoint)
#

set -euo pipefail

# ==============================================================================
# CONFIGURATION - Edit this section to customize your benchmark
# ==============================================================================

# Mode: "offline" or "online"
MODE="online"

# ---------------------- OFFLINE MODE SETTINGS ----------------------
# Only used when MODE="offline"
OFFLINE_MODEL="Qwen/Qwen3-0.6B"
OFFLINE_NUM_REQS=100
OFFLINE_ICL=512                    # Input context length
OFFLINE_OCL=128                    # Output context length
OFFLINE_THROUGHPUT_DIR="/workspace/results"
OFFLINE_TENSOR_PARALLEL_SIZE=1
OFFLINE_PIPELINE_PARALLEL_SIZE=1
OFFLINE_GPU_MEMORY_UTILIZATION=0.9
OFFLINE_MAX_NUM_BATCHED_TOKENS=8192
OFFLINE_EXTRA_ARGS=""              # Additional CLI args, space-separated

# ---------------------- ONLINE MODE SETTINGS ----------------------
# Only used when MODE="online"
ONLINE_MODEL="Qwen/Qwen3-0.6B"

# Server settings
SERVER_HOST="0.0.0.0"
SERVER_PORT=8000
SERVER_TENSOR_PARALLEL_SIZE=1
SERVER_PIPELINE_PARALLEL_SIZE=1
SERVER_MAX_NUM_BATCHED_TOKENS=8192
SERVER_GPU_MEMORY_UTILIZATION=0.75
SERVER_GPU_NAME=""                 # Optional descriptive label (e.g., "A100-80GB")
SERVER_GPU_COUNT=""                # Optional integer count
SERVER_EXTRA_ARGS=""               # Additional server CLI args
SERVER_WAIT_RETRIES=10000
SERVER_WAIT_DELAY_SECS=5

# Client settings
CLIENT_HOST=""                     # Leave empty to use http://127.0.0.1:$SERVER_PORT
CLIENT_ENDPOINT="/v1/chat/completions"
CLIENT_USERS=10
CLIENT_REQUESTS_PER_USER=5
CLIENT_API_KEY=""
CLIENT_API_KEY_ENV=""              # Env var containing API key
CLIENT_REQUEST_TIMEOUT_SECS=120
CLIENT_MAX_RETRIES=3
CLIENT_RETRY_DELAY_MS=100
CLIENT_OUTPUT_TOKENS=128
CLIENT_OUTPUT_VARY=20
CLIENT_OUTPUT_LOGNORM_MU=""        # Use lognormal sampling instead of fixed
CLIENT_OUTPUT_LOGNORM_SIGMA=""
CLIENT_RANDOM_REQUESTS=true
CLIENT_VERBOSE=false
CLIENT_RESULTS_CSV="/tmp/batchbench_results.csv"
CLIENT_EXTRA_ARGS=""

# Server reporting (optional - posts results to a BatchBench server)
REPORT_SERVER_URL="https://titan-6-1.tail5ef35.ts.net"
REPORT_PROJECT_NAME="test"
REPORT_EXPERIMENT_NAME="test1"

# ---------------------- DATASET GENERATION SETTINGS ----------------------
# Used for online mode when dataset doesn't exist
DATASET_PATH="/tmp/batchbench_requests.jsonl"
GENERATE_COUNT=100
GENERATE_PREFIX_OVERLAP=0.0
GENERATE_APPROX_INPUT_TOKENS=256
GENERATE_TOKENIZER_MODEL=""        # Leave empty to use ONLINE_MODEL
GENERATE_TOKEN_TOLERANCE=""
GENERATE_HUGGINGFACE_TOKEN=""
GENERATE_EXTRA_ARGS=""

# ==============================================================================
# CONFIG FILE GENERATION - Do not edit below unless you know what you're doing
# ==============================================================================

CONFIG_FILE="/tmp/batchbench_config.yaml"

generate_yaml() {
    # Helper function to output a YAML value (null if empty)
    yaml_val() {
        if [ -n "$1" ]; then
            echo "$1"
        else
            echo "null"
        fi
    }
    
    # Helper for boolean values
    yaml_bool() {
        case "$1" in
            true|True|TRUE|1|yes|Yes|YES) echo "true" ;;
            *) echo "false" ;;
        esac
    }
    
    # Helper for quoted strings (null if empty)
    yaml_str() {
        if [ -n "$1" ]; then
            echo "\"$1\""
        else
            echo "null"
        fi
    }
    
    # Helper for integers (null if empty)
    yaml_int() {
        if [ -n "$1" ]; then
            echo "$1"
        else
            echo "null"
        fi
    }
    
    # Helper for floats (null if empty)
    yaml_float() {
        if [ -n "$1" ]; then
            echo "$1"
        else
            echo "null"
        fi
    }

    cat > "$CONFIG_FILE" << YAML_EOF
# BatchBench Configuration - Auto-generated by launch_batchbench.sh
# Generated at: $(date -Iseconds)

mode: ${MODE}

offline:
  model: $(yaml_str "$OFFLINE_MODEL")
  num_reqs: $(yaml_int "$OFFLINE_NUM_REQS")
  icl: $(yaml_int "$OFFLINE_ICL")
  ocl: $(yaml_int "$OFFLINE_OCL")
  throughput_dir: $(yaml_str "$OFFLINE_THROUGHPUT_DIR")
  tensor_parallel_size: $(yaml_int "$OFFLINE_TENSOR_PARALLEL_SIZE")
  pipeline_parallel_size: $(yaml_int "$OFFLINE_PIPELINE_PARALLEL_SIZE")
  gpu_memory_utilization: $(yaml_float "$OFFLINE_GPU_MEMORY_UTILIZATION")
  max_num_batched_tokens: $(yaml_int "$OFFLINE_MAX_NUM_BATCHED_TOKENS")
  extra_args: [${OFFLINE_EXTRA_ARGS}]

online:
  model: $(yaml_str "$ONLINE_MODEL")
  
  server:
    host: $(yaml_str "$SERVER_HOST")
    port: $(yaml_int "$SERVER_PORT")
    tensor_parallel_size: $(yaml_int "$SERVER_TENSOR_PARALLEL_SIZE")
    pipeline_parallel_size: $(yaml_int "$SERVER_PIPELINE_PARALLEL_SIZE")
    max_num_batched_tokens: $(yaml_int "$SERVER_MAX_NUM_BATCHED_TOKENS")
    gpu_memory_utilization: $(yaml_float "$SERVER_GPU_MEMORY_UTILIZATION")
    gpu_name: $(yaml_str "$SERVER_GPU_NAME")
    gpu_count: $(yaml_int "$SERVER_GPU_COUNT")
    extra_args: [${SERVER_EXTRA_ARGS}]
    wait_retries: $(yaml_int "$SERVER_WAIT_RETRIES")
    wait_delay_secs: $(yaml_int "$SERVER_WAIT_DELAY_SECS")
    health_url: null

  client:
    host: $(yaml_str "$CLIENT_HOST")
    endpoint: $(yaml_str "$CLIENT_ENDPOINT")
    users: $(yaml_int "$CLIENT_USERS")
    requests_per_user: $(yaml_int "$CLIENT_REQUESTS_PER_USER")
    api_key: $(yaml_str "$CLIENT_API_KEY")
    api_key_env: $(yaml_str "$CLIENT_API_KEY_ENV")
    request_timeout_secs: $(yaml_int "$CLIENT_REQUEST_TIMEOUT_SECS")
    max_retries: $(yaml_int "$CLIENT_MAX_RETRIES")
    retry_delay_ms: $(yaml_int "$CLIENT_RETRY_DELAY_MS")
    output_tokens: $(yaml_int "$CLIENT_OUTPUT_TOKENS")
    output_vary: $(yaml_int "$CLIENT_OUTPUT_VARY")
    output_lognorm_mu: $(yaml_float "$CLIENT_OUTPUT_LOGNORM_MU")
    output_lognorm_sigma: $(yaml_float "$CLIENT_OUTPUT_LOGNORM_SIGMA")
    random_requests: $(yaml_bool "$CLIENT_RANDOM_REQUESTS")
    verbose: $(yaml_bool "$CLIENT_VERBOSE")
    results_csv: $(yaml_str "$CLIENT_RESULTS_CSV")
    server_url: $(yaml_str "$REPORT_SERVER_URL")
    project_name: $(yaml_str "$REPORT_PROJECT_NAME")
    experiment_name: $(yaml_str "$REPORT_EXPERIMENT_NAME")
    extra_args: [${CLIENT_EXTRA_ARGS}]

generate:
  dataset_path: $(yaml_str "$DATASET_PATH")
  count: $(yaml_int "$GENERATE_COUNT")
  prefix_overlap: $(yaml_float "$GENERATE_PREFIX_OVERLAP")
  approx_input_tokens: $(yaml_int "$GENERATE_APPROX_INPUT_TOKENS")
  tokenizer_model: $(yaml_str "${GENERATE_TOKENIZER_MODEL:-$ONLINE_MODEL}")
  token_tolerance: $(yaml_int "$GENERATE_TOKEN_TOLERANCE")
  huggingface_token: $(yaml_str "$GENERATE_HUGGINGFACE_TOKEN")
  extra_args: [${GENERATE_EXTRA_ARGS}]
YAML_EOF

    echo "Generated config file: $CONFIG_FILE"
}

# ==============================================================================
# MAIN EXECUTION
# ==============================================================================

main() {
    echo "=========================================="
    echo "BatchBench Container Launcher"
    echo "=========================================="
    echo ""
    
    # Generate the YAML configuration
    echo "Generating YAML configuration..."
    generate_yaml
    echo ""
    
    # Display the generated config for debugging
    echo "Generated configuration:"
    echo "----------------------------------------"
    cat "$CONFIG_FILE"
    echo "----------------------------------------"
    echo ""
    
    # Export the config file path for the entrypoint
    export CONFIG_FILE
    
    # Run the BatchBench entrypoint
    echo "Starting BatchBench (mode: $MODE)..."
    echo ""
    
    # Check if we're in the container (batchbench-entrypoint exists) or running locally
    if command -v batchbench-entrypoint &> /dev/null; then
        # Inside container - use the installed entrypoint
        exec batchbench-entrypoint
    elif [ -f "/usr/local/bin/batchbench-entrypoint" ]; then
        # Fallback to absolute path
        exec /usr/local/bin/batchbench-entrypoint
    else
        # Running locally or entrypoint not installed - run the Python script directly
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        if [ -f "$SCRIPT_DIR/run_docker.py" ]; then
            exec python3 "$SCRIPT_DIR/run_docker.py"
        else
            echo "ERROR: Cannot find run_docker.py or batchbench-entrypoint"
            echo "Make sure you're running this from the docker/ directory or inside a batchbench container"
            exit 1
        fi
    fi
}

# Run main function
main "$@"
